#!/usr/bin/env bash
# This a Bash script that displays listening ports:
#+ This only shows listening sockets
#+ This shows the PID and name of the program to which each socket belongs

sudo netstat -lp
