#!/usr/bin/env bash
# The scriptwill do the following:
#  It creates the file '/var/run/myscript.pid' containing its PID
#  Displays 'To infinity and beyond' indefinitely
#  Displays 'I hate the kill command' when receiving a SIGTERM signal
#  Displays 'Y U no love me?!' when receiving a SIGINT signal
#  Deletes the file '/var/run/myscript.pid' and terminates itself when receiving a SIGQUIT or SIGTERM signal

pidfile="/var/run/myscript.pid"

if [ ! -e "$pidfile" ]; then
	touch "$pidfile"
fi

sleep 2 &

echo "$!" > "$pidfile"

# displays I hate the kill command, deletes the file and exits on receiveing the SIGQUIT or SIGTERM signal 
trap 'echo "I hate the kill command"; rm "$pidfile"; exit' SIGTERM SIGQUIT

# displays Y U no love me?! on receiving the SIGINT signal
trap 'echo "Y U no love me?!"' SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
